/**
 * PLACEHOLDER -- this file is normally auto-generated by `wasm-pack build`
 * (see .github/workflows/build-wasm.yml) and will be OVERWRITTEN the first
 * time that workflow runs. It's hand-written for now purely so TypeScript
 * can type-check `solverClient.ts` before the real WASM bindings exist.
 *
 * Do not add logic here -- this only describes the shape wasm-bindgen
 * will produce for our two #[wasm_bindgen] items in solver-core/src/lib.rs.
 */

/** Initializes the wasm module. Must be awaited before calling solve_lpp. */
export default function init(
  moduleOrPath?: RequestInfo | URL | Response | BufferSource | WebAssembly.Module
): Promise<unknown>;

/**
 * Calls into the Rust solver. Constraints/objective are plain JS objects
 * (matching lib/types.ts's Constraint/Objective shapes); the return value
 * matches SolverResult. Thrown as a JS exception on malformed input.
 */
export function solve_lpp(
  constraints: unknown,
  objective: unknown,
  restrictXNonneg: boolean,
  restrictYNonneg: boolean
): unknown;
